server:
  port: 8081

spring:
  datasource:
    url: Удалено правообладателем 
    username: Удалено правообладателем
    password: Удалено правообладателем
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
