server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/TaskDB_version2?currentSchema=public
    username: postgres
    password: Tamikwqwqw1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true